### PR TITLE
Fix usages of deprecated AbstractArchiveTask.classifier, AbstractArchiveTask.extension

### LINKED ISSUE #82: The AbstractArchiveTask.classifier, extension property has been deprecated
https://docs.gradle.org/7.4.2/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:classifier

Build scan: https://scans.gradle.com/s/d6ybdmfkporew/deprecations?expanded=WyI0Il0&expanded-stacktrace=WyI2Il0&focused-stack-frame=0-0-5 , https://scans.gradle.com/s/d6ybdmfkporew/deprecations?expanded=WyIxMiJd&expanded-stacktrace=WyIxNCJd&focused-stack-frame=1-0-5

stacktrace:

```


at org.gradle.api.tasks.bundling.AbstractArchiveTask.getClassifier(AbstractArchiveTask.java:422) |  
-- | --
  |   | at org.gradle.api.tasks.bundling.Jar_Decorated.getClassifier(Unknown Source) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59) |  
  |   | at org.gradle.api.tasks.bundling.Jar_Decorated.getProperty(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.model.DependencyDescriptor.make(DependencyDescriptor.groovy:51) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.model.DependencyDescriptor$make.call(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils.collectDependencies(KarafFeaturesUtils.groovy:74) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils$collectDependencies$0.callStatic(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils$_collectDependencies_closure1.doCall(KarafFeaturesUtils.groovy:43) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) |  
  |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:59) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$walkDeps$0.callStatic(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$walkDeps$0.callStatic(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure3.doCall(KarafUtils.groovy:39) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) |  
  |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) |  
  |   | at groovy.lang.Closure.call(Closure.java:412) |  
  |   | at groovy.lang.Closure.call(Closure.java:428) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:37) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$walkDeps.call(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils.collectDependencies(KarafFeaturesUtils.groovy:41) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils$collectDependencies.call(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.model.DependencyResolver.resolve(DependencyResolver.groovy:27) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.model.DependencyResolver$resolve.call(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$_generateFeatures_closure2$_closure4$_closure5.doCall(KarafFeaturesTask.groovy:104) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$_generateFeatures_closure2$_closure4$_closure5.doCall(KarafFeaturesTask.groovy) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) |  
  |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) |  
  |   | at groovy.lang.Closure.call(Closure.java:412) |  
  |   | at groovy.lang.Closure.call(Closure.java:406) |  
  |   | at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:153) |  
  |   | at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:74) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$_generateFeatures_closure2$_closure4.doCall(KarafFeaturesTask.groovy:69) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) |  
  |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) |  
  |   | at groovy.lang.Closure.call(Closure.java:412) |  
  |   | at groovy.lang.Closure.call(Closure.java:428) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$_generateFeatures_closure2.doCall(KarafFeaturesTask.groovy:68) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$_generateFeatures_closure2.doCall(KarafFeaturesTask.groovy) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) |  
  |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) |  
  |   | at groovy.lang.Closure.call(Closure.java:412) |  
  |   | at groovy.lang.Closure.call(Closure.java:406) |  
  |   | at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:153) |  
  |   | at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:74) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask.generateFeatures(KarafFeaturesTask.groovy:64) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask$generateFeatures.callCurrent(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesTask.run(KarafFeaturesTask.groovy:53) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568)
```

extension:

```
at org.gradle.api.tasks.bundling.AbstractArchiveTask.getExtension(AbstractArchiveTask.java:378) |  
-- | --
  |   | at org.gradle.api.tasks.bundling.Jar_Decorated.getExtension(Unknown Source) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59) |  
  |   | at org.gradle.api.tasks.bundling.Jar_Decorated.getProperty(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.model.DependencyDescriptor.make(DependencyDescriptor.groovy:51) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.model.DependencyDescriptor$make.call(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils.collectDependencies(KarafFeaturesUtils.groovy:74) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils$collectDependencies$0.callStatic(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils$_collectDependencies_closure1.doCall(KarafFeaturesUtils.groovy:43) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) |  
  |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:59) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$walkDeps$0.callStatic(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$walkDeps$0.callStatic(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$_walkDeps_closure3.doCall(KarafUtils.groovy:39) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:568) |  
  |   | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) |  
  |   | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) |  
  |   | at groovy.lang.Closure.call(Closure.java:412) |  
  |   | at groovy.lang.Closure.call(Closure.java:428) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils.walkDeps(KarafUtils.groovy:37) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.KarafUtils$walkDeps.call(Unknown Source) |  
  |   | at com.github.lburgazzoli.gradle.plugin.karaf.features.KarafFeaturesUtils.collectDependencies(KarafFeatu
```

### PR DESCRIPTION
**Pull request by vlsi**
fixes #82

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@vlsi I'm doing something similar here https://github.com/lburgazzoli/gradle-karaf-plugin/tree/g7

**Comment by vlsi** [comment]
The drawback of moving to Gradle 7 for plugins is the resulting plugin will be incompatible with Gradle <7.

Frankly speaking, I'm bumping pgjdbc to 7 in any case, so it does not impact much, however, staying with 6.9 for a while would help people to upgrade.

**Comment by lburgazzoli** [comment]
> The drawback of moving to Gradle 7 for plugins is the resulting plugin will be incompatible with Gradle <7.
> 
> Frankly speaking, I'm bumping pgjdbc to 7 in any case, so it does not impact much, however, staying with 6.9 for a while would help people to upgrade.

If you have any time to help maintaining version fro gradle < 7, I'm ok, but I'm likely not be able to do so

**Comment by vlsi** [comment]
>If you have any time to help maintaining version fro gradle < 7, I'm ok, but I'm likely not be able to do so

That's fair.

On the other hand, Gradle 7 + composite builds might indeed be easier to support.

**Pull request merged**
