### PR TITLE
Fix for issue #60 that prevents composite build jar from being copied…

### PR DESCRIPTION
**Pull request by crosscontrol**
This fixes issue number 60 by checking for an existing artifact before attempting to get a jar from an included project. This accounts for included (composite) builds.

This has been used for multiple weeks now with no issues and corrects the problem.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
can you please rebase and fix the conflict ?

**Comment by crosscontrol** [comment]
Hi Luca,

I started looking at the rebase on my local system but it will be a little while before I can properly test the rebase with the changes that have been made since the original pull request. I don't feel comfortable submitting an update until I can properly understand and test the changes. Please let me know if you can wait a while otherwise if its time sensitive I recommend trying to perform the rebase yourself. I'll try to get to it as in a timely manner if it can wait.

**Comment by lburgazzoli** [comment]
no rush

**Comment by lburgazzoli** [comment]
@crosscontrol  there's a conflict, can you please rebase ?

**Comment by lburgazzoli** [comment]
closed as outdated

**Pull request closed without merging**
