### PR TITLE
Changes to README file

### PR DESCRIPTION
**Pull request by eximius313**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
can you rebase ?

**Comment by eximius313** [comment]
it failed again

**Comment by eximius313** [comment]
@lburgazzoli I've rebased, but it failed again. What I suppose to do?

**Comment by lburgazzoli** [comment]
I won't be able to look at the issue for the entire week unfortunately so if you have time, please have a look at the failing test

**Comment by eximius313** [comment]
I was just changing README not code....

**Comment by lburgazzoli** [comment]
can you please rebase ?

**Comment by eximius313** [comment]
I don't have time anymore, sorry

**Pull request merged**
