### PR TITLE
Wrap protocol instructions are separated with a dollar sign

### LINKED ISSUE #19: Adding bundle instructions in the features
I have a transitive dependency that results in a bundle line like this:

```xml
    <bundle>wrap:mvn:org.bitcoinj/bitcoinj-core/0.13.6</bundle>
```

However, since it is not an OSGi package, and I [desperately] need to attach a fragment to it, I need to assign a symbolic name to it, like this:

```xml
    <bundle>wrap:mvn:org.bitcoinj/bitcoinj-core/0.13.6$Bundle-SymbolicName=bitcoinj</bundle>
```

However, I can't quite figure out how this should be done with this plugin.

I tried different variations of this but none worked:

```groovy
bundle('wrap:mvn:org.bitcoinj/bitcoinj-core/0.13.6') {
    it.instruction "Bundle-SymbolicName", "bitcoinj"
}
```

Any advice? Thanks!

### PR DESCRIPTION
**Pull request by yrashk**
See https://ops4j1.jira.com/wiki/display/paxurl/Wrap+Protocol

Closes #19

### CODE REVIEW

**Comment by lburgazzoli** [comment]
thx

**Comment by yrashk** [comment]
Will you make a new release soon?

On Wednesday, 20 April 2016, Luca Burgazzoli <notifications@github.com>
wrote:

> thx
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lburgazzoli/gradle-karaf-plugin/pull/20#issuecomment-212581906>
>


-- 
Y.

**Comment by lburgazzoli** [comment]
tomorrow morning as first task

**Comment by lburgazzoli** [comment]
v0.0.27 released

**Comment by yrashk** [comment]
Thank you very much!

On Wednesday, 20 April 2016, Luca Burgazzoli <notifications@github.com>
wrote:

> v0.0.27 released
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lburgazzoli/gradle-karaf-plugin/pull/20#issuecomment-212747131>
>


-- 
Y.

**Pull request merged**
